Варя

In [1]:
import pandas as pd

data = [
    [1, 602.4764, 1, 0.60586490, 3.94, 9.59],
    [2, 849.4722, 1, 1.51616780, 5.21, 16.12],
    [3, 588.9964, 0, 0.11193536, 5.29, 8.20],
    [4, 485.2265, 1, -1.63322004, 5.20, 8.86],
    [5, 533.9728, 1, 1.03868892, 3.79, 7.72],
    [6, 319.4603, 1, 0.02996776, 2.43, 7.09],
    [7, 758.3876, 1, 0.49758471, 2.07, 12.75],
    [8, 553.6819, 1, -0.45707216, 5.11, 5.34],
    [9, 1126.1162, 0, 0.34245234, 5.29, 19.83],
    [10, 1032.1622, 0, 0.61299423, 4.30, 19.66],
    [11, 487.8605, 1, 0.69772299, 4.19, 5.67],
    [12, 457.7085, 1, 0.76131872, 4.95, 6.02],
    [13, 855.6251, 0, 0.03928727, 4.48, 17.13],
    [14, 315.0307, 1, 0.11193345, 4.82, 5.30],
    [15, 634.0165, 0, -1.42991475, 5.26, 11.96],
    [16, 666.6918, 1, -0.30524536, 6.23, 6.74],
    [17, 793.5767, 0, -0.86251963, 4.99, 12.02],
    [18, 584.3867, 0, -0.54959894, 3.11, 15.50],
    [19, 791.0435, 0, -1.53695203, 2.96, 19.17],
    [20, 656.0516, 0, 0.89337153, 4.75, 12.83],
    [21, 1094.4149, 0, -0.32566595, 5.23, 19.58],
    [22, 655.5124, 1, 0.66682947, 6.05, 9.25],
    [23, 1150.0168, 0, -1.33282143, 5.56, 18.97],
    [24, 746.7747, 0, -0.06261464, 4.57, 16.89],
    [25, 642.6604, 0, -0.78883763, 5.32, 7.87],
    [26, 489.9785, 0, -0.60836159, 4.71, 5.05],
    [27, 340.9247, 0, -1.07267047, 5.10, 7.63],
    [28, 792.6325, 0, -0.14756846, 3.85, 17.65],
    [29, 879.6555, 1, 1.25210055, 7.17, 7.60],
    [30, 845.7812, 1, 2.21678233, 4.07, 13.12],
    [31, 765.0503, 0, 0.44917679, 3.01, 15.77],
    [32, 952.1395, 1, 2.01691869, 3.52, 18.11],
    [33, 547.3990, 1, 0.18791808, 5.55, 6.24],
    [34, 792.5086, 0, -1.23780073, 5.33, 14.64],
    [35, 935.8928, 0, -0.91885278, 4.69, 18.14],
    [36, 651.1782, 1, -0.42455182, 7.46, 7.34],
    [37, 910.9213, 0, -1.69551550, 5.13, 16.95],
    [38, 600.9583, 1, 1.60856445, 5.39, 8.96],
    [39, 853.8305, 0, -1.50363965, 4.86, 14.19],
    [40, 619.2623, 1, 0.74928088, 4.43, 6.68],
    [41, 984.5403, 0, 0.17015781, 4.88, 18.01],
    [42, 897.8056, 0, -0.11725482, 4.72, 16.47],
    [43, 451.4683, 1, 1.02881243, 3.99, 7.96],
    [44, 449.3056, 1, -0.07614553, 5.20, 5.38],
    [45, 389.4154, 0, -2.53571271, 5.23, 6.02],
    [46, 1040.7070, 0, 0.38268936, 4.76, 18.11],
    [47, 308.8964, 1, 0.73492380, 4.32, 5.20],
    [48, 477.9211, 1, -1.92820893, 4.77, 5.49],
    [49, 462.4170, 1, -0.88076598, 4.37, 5.98],
    [50, 648.6353, 0, -1.33121205, 6.46, 10.58],
    [51, 964.5105, 0, -0.28042628, 6.09, 17.33],
    [52, 912.9571, 1, 0.41836132, 6.33, 14.85],
    [53, 355.5470, 0, -0.59599496, 4.49, 9.67],
    [54, 893.1200, 0, -2.03467905, 5.86, 15.55],
    [55, 1004.8698, 0, -0.76875281, 7.22, 15.81],
    [56, 527.7453, 1, -0.17563545, 6.21, 9.74],
    [57, 917.1995, 0, -1.12818711, 4.07, 19.12],
    [58, 776.1643, 1, 1.14166024, 5.09, 5.84],
    [59, 569.5142, 1, -1.51571108, 3.15, 11.67],
    [60, 929.6657, 0, -0.35827568, 5.14, 17.77],
    [61, 749.7365, 0, -0.18349659, 5.54, 9.41],
    [62, 742.1204, 1, 0.75303204, 6.25, 8.95],
    [63, 646.2287, 1, 1.15124068, 3.83, 12.52],
    [64, 726.1743, 1, 0.43179849, 6.26, 6.99],
    [65, 235.2603, 1, -0.15743046, 3.83, 6.29],
    [66, 1242.1189, 1, 1.38400904, 6.15, 17.99],
    [67, 747.6336, 0, -0.90708013, 4.46, 12.97],
    [68, 438.8374, 1, -0.87716576, 5.68, 6.96],
    [69, 856.6226, 1, -0.34487915, 6.48, 15.48],
    [70, 949.8196, 0, -0.55716175, 4.21, 19.83],
    [71, 899.5066, 0, 1.45249648, 6.37, 15.30],
    [72, 859.8831, 0, 0.28156827, 4.37, 15.50],
    [73, 771.5912, 0, -0.08314961, 5.89, 11.13],
    [74, 475.9371, 1, 0.33863222, 4.43, 6.86],
    [75, 612.4375, 1, 1.80009869, 4.33, 9.60],
    [76, 859.1933, 1, -0.42226076, 3.83, 13.97],
    [77, 760.7470, 0, -0.72734316, 4.23, 17.07],
    [78, 703.0805, 1, 0.06356043, 5.61, 10.17],
    [79, 500.3177, 0, -0.96590077, 6.14, 10.66],
    [80, 919.5385, 0, -0.16100740, 4.56, 14.42],
    [81, 511.7697, 1, 0.50275661, 5.76, 8.28],
    [82, 905.5503, 0, -1.38658912, 5.28, 15.92],
    [83, 478.9086, 1, -0.39319926, 2.64, 10.64],
    [84, 690.2173, 0, 0.25916614, 4.73, 8.35],
    [85, 1149.3760, 0, 0.35988028, 6.93, 19.85],
    [86, 781.0139, 1, 2.00669566, 4.86, 9.76],
    [87, 688.8061, 1, 0.46135385, 5.21, 8.84],
    [88, 724.5347, 0, -1.69895474, 5.78, 15.20],
    [89, 556.9335, 1, -1.05935119, 6.23, 6.14],
    [90, 608.3318, 1, 1.05638981, 2.65, 11.14],
    [91, 751.5196, 0, -2.08060446, 4.55, 19.38],
    [92, 669.9593, 0, -2.48505275, 5.51, 9.49],
    [93, 780.1950, 1, -1.37509256, 5.43, 10.37],
    [94, 891.6383, 1, -2.14331394, 6.19, 16.08],
    [95, 986.1404, 0, 1.26482060, 4.76, 16.67],
    [96, 1045.7784, 0, -0.53633928, 5.54, 19.74],
    [97, 589.7696, 1, 0.19754699, 6.01, 7.03],
    [98, 901.2577, 0, -1.84221671, 6.89, 16.42],
    [99, 1070.6113, 0, -0.71746855, 4.98, 19.83],
    [100, 764.0417, 1, 0.76265894, 4.78, 10.71],
]

df = pd.DataFrame(data, columns=["index", "Y", "Y_bin", "X1", "X2", "X3"]).set_index("index")
df.index.name = None

df

             Y  Y_bin        X1    X2     X3
1     602.4764      1  0.605865  3.94   9.59
2     849.4722      1  1.516168  5.21  16.12
3     588.9964      0  0.111935  5.29   8.20
4     485.2265      1 -1.633220  5.20   8.86
5     533.9728      1  1.038689  3.79   7.72
..         ...    ...       ...   ...    ...
96   1045.7784      0 -0.536339  5.54  19.74
97    589.7696      1  0.197547  6.01   7.03
98    901.2577      0 -1.842217  6.89  16.42
99   1070.6113      0 -0.717469  4.98  19.83
100   764.0417      1  0.762659  4.78  10.71

[100 rows x 5 columns]

олеся

In [2]:
import pandas as pd

data = [
    [1, 502.4651, 1, -0.17682811, 4.90, 5.60],
    [2, 690.3162, 1, 0.71837086, 3.64, 10.35],
    [3, 746.0330, 0, -0.38757678, 4.60, 12.31],
    [4, 817.9587, 0, -0.09956920, 5.73, 13.59],
    [5, 482.2451, 1, -0.09458290, 4.30, 9.32],
    [6, 903.7532, 1, 1.34947532, 5.61, 13.24],
    [7, 876.0702, 1, 1.14821662, 4.31, 16.01],
    [8, 729.2421, 0, 2.20023169, 4.82, 14.39],
    [9, 503.7217, 1, 1.87726454, 6.38, 5.64],
    [10, 1048.4463, 0, -0.29170273, 5.45, 19.42],
    [11, 1056.8261, 0, 0.45954520, 4.65, 17.10],
    [12, 402.2001, 1, 1.58961959, 3.64, 5.93],
    [13, 681.0198, 1, 0.29339327, 4.86, 11.51],
    [14, 453.2202, 0, 0.33251089, 3.31, 10.18],
    [15, 619.8189, 1, 0.30205795, 5.99, 9.67],
    [16, 778.5002, 0, -0.89477736, 3.91, 15.82],
    [17, 894.7336, 0, -0.22820108, 4.38, 15.24],
    [18, 445.0446, 1, -2.24594299, 3.43, 11.16],
    [19, 595.7433, 1, 1.93994890, 5.12, 9.56],
    [20, 651.3341, 1, 1.59143969, 5.50, 8.30],
    [21, 660.6948, 1, 0.04393905, 4.93, 11.49],
    [22, 766.9964, 1, 0.11593086, 5.09, 10.26],
    [23, 883.0021, 0, 1.06621671, 6.14, 16.31],
    [24, 564.6083, 1, 1.41378382, 3.99, 7.11],
    [25, 814.7596, 0, 0.33894512, 4.21, 19.80],
    [26, 763.2840, 1, 1.41064053, 6.11, 9.46],
    [27, 654.3485, 0, 1.32403797, 4.55, 10.92],
    [28, 613.2903, 1, -1.17021972, 6.10, 11.09],
    [29, 1009.6056, 0, -0.80291008, 4.49, 18.39],
    [30, 560.8526, 1, -0.69907970, 5.43, 10.26],
    [31, 850.3433, 0, -1.40171287, 2.46, 15.40],
    [32, 610.6090, 1, 1.32309440, 5.08, 7.48],
    [33, 831.8892, 0, 0.13607267, 4.78, 15.69],
    [34, 737.7426, 0, 0.31964498, 5.76, 11.27],
    [35, 799.8293, 0, 0.47230500, 4.78, 11.91],
    [36, 535.2379, 0, -0.75691535, 5.80, 10.05],
    [37, 684.7639, 1, -0.04299866, 3.47, 12.46],
    [38, 920.4657, 0, 1.70225490, 6.05, 17.23],
    [39, 663.7606, 1, 0.33269653, 4.25, 11.51],
    [40, 542.6915, 0, -0.48316063, 4.97, 8.64],
    [41, 804.6067, 0, -0.78761619, 5.56, 15.09],
    [42, 934.1951, 0, -0.57955206, 5.10, 17.12],
    [43, 644.1492, 1, 1.93528014, 3.31, 11.96],
    [44, 888.2361, 0, -1.14797294, 5.05, 18.53],
    [45, 525.9876, 1, -0.70249486, 4.59, 10.91],
    [46, 681.8305, 0, 1.30293395, 6.04, 14.07],
    [47, 671.9874, 1, 0.29566123, 5.37, 10.09],
    [48, 593.3846, 1, -2.19354870, 5.36, 12.13],
    [49, 583.2993, 1, 0.53743414, 5.37, 9.28],
    [50, 952.4524, 0, 1.81583585, 5.04, 17.86],
    [51, 388.1860, 1, -1.08733391, 5.88, 5.30],
    [52, 487.1710, 0, -1.63183496, 3.84, 9.45],
    [53, 547.3332, 1, 0.96094509, 6.12, 5.92],
    [54, 681.9273, 0, -1.10048602, 5.01, 15.04],
    [55, 521.2037, 1, 0.57820800, 4.67, 11.88],
    [56, 871.5162, 0, -0.03830002, 5.46, 15.63],
    [57, 620.3049, 0, -0.29414431, 3.73, 13.75],
    [58, 1125.1189, 1, 1.60322556, 3.06, 19.26],
    [59, 889.0834, 0, 0.68863681, 5.80, 17.97],
    [60, 809.7776, 1, 1.55625927, 5.65, 10.83],
    [61, 728.3342, 1, 0.46107200, 3.18, 12.25],
    [62, 1054.9213, 0, 0.94993697, 6.55, 15.93],
    [63, 510.9949, 0, -1.47730910, 6.44, 8.64],
    [64, 847.1549, 1, 0.51520161, 4.28, 13.19],
    [65, 417.6778, 1, -0.30115272, 6.25, 5.19],
    [66, 888.8529, 0, 0.47323239, 4.55, 17.82],
    [67, 340.9074, 1, -2.27562199, 4.22, 5.53],
    [68, 815.4790, 1, 1.47496646, 5.86, 7.73],
    [69, 432.3126, 1, 1.12304894, 3.11, 11.18],
    [70, 808.5828, 0, 0.91740449, 4.40, 17.68],
    [71, 547.7986, 1, 1.22160729, 4.84, 5.46],
    [72, 712.0707, 0, 0.15981311, 4.93, 9.89],
    [73, 790.1503, 1, 2.36183411, 3.79, 14.52],
    [74, 893.8284, 1, 0.37523188, 6.06, 14.74],
    [75, 762.1728, 0, 0.19141270, 5.35, 14.29],
    [76, 771.9709, 0, -0.93258682, 4.25, 19.25],
    [77, 399.8408, 1, -1.26189448, 4.62, 7.56],
    [78, 615.9784, 1, 0.75681062, 5.40, 7.06],
    [79, 631.1918, 1, -0.11425418, 5.00, 7.24],
    [80, 686.3330, 1, -1.06792161, 5.06, 12.05],
    [81, 1008.5738, 0, -0.14434499, 5.38, 16.43],
    [82, 962.2650, 0, 0.03638650, 4.71, 19.80],
    [83, 627.6799, 1, 2.32160377, 5.33, 6.18],
    [84, 429.8156, 1, -2.29115528, 5.76, 5.31],
    [85, 978.6676, 0, 0.16602997, 4.93, 16.95],
    [86, 845.2108, 0, 1.51005112, 5.53, 15.17],
    [87, 709.4787, 0, -0.43027963, 6.56, 13.30],
    [88, 1142.1668, 0, 1.38147848, 6.24, 18.84],
    [89, 406.0536, 1, -0.36897589, 4.72, 6.13],
    [90, 658.5763, 1, -0.74990216, 5.16, 11.02],
    [91, 952.0544, 0, 1.24102268, 5.32, 15.34],
    [92, 818.6246, 1, 1.22080623, 5.94, 12.40],
    [93, 728.9191, 0, -0.33326293, 4.84, 14.95],
    [94, 1038.2558, 1, 1.41871530, 4.36, 17.64],
    [95, 695.8993, 1, -1.97334555, 5.91, 11.15],
    [96, 982.3034, 0, -1.12898675, 5.22, 19.61],
    [97, 436.4412, 1, -1.24785144, 2.67, 11.05],
    [98, 719.8061, 1, 1.68572062, 4.82, 12.70],
    [99, 1197.5118, 1, 1.44798107, 5.97, 15.75],
    [100, 623.5166, 0, -1.13376548, 5.81, 9.98],
]

df = pd.DataFrame(data, columns=["index", "Y", "Y_bin", "X1", "X2", "X3"]).set_index("index")
df.index.name = None

df

             Y  Y_bin        X1    X2     X3
1     502.4651      1 -0.176828  4.90   5.60
2     690.3162      1  0.718371  3.64  10.35
3     746.0330      0 -0.387577  4.60  12.31
4     817.9587      0 -0.099569  5.73  13.59
5     482.2451      1 -0.094583  4.30   9.32
..         ...    ...       ...   ...    ...
96    982.3034      0 -1.128987  5.22  19.61
97    436.4412      1 -1.247851  2.67  11.05
98    719.8061      1  1.685721  4.82  12.70
99   1197.5118      1  1.447981  5.97  15.75
100   623.5166      0 -1.133765  5.81   9.98

[100 rows x 5 columns]

катя

In [3]:
import pandas as pd

data = [
    [1, 821.5460, 0, -0.937613685, 4.01, 14.25],
    [2, 969.5544, 0, 0.194259052, 4.66, 16.30],
    [3, 696.9056, 1, 1.197006514, 5.66, 8.04],
    [4, 948.9634, 0, 0.367137427, 5.85, 17.28],
    [5, 462.7538, 1, 1.935985945, 5.99, 6.78],
    [6, 890.8595, 1, 1.664792711, 5.46, 16.40],
    [7, 773.8783, 1, -1.361057369, 4.05, 13.78],
    [8, 771.2548, 0, -0.031781102, 3.69, 13.89],
    [9, 1128.9429, 0, 3.079385190, 3.60, 19.15],
    [10, 346.2715, 1, -0.422751990, 5.08, 5.07],
    [11, 959.0428, 0, -0.841341027, 5.68, 15.02],
    [12, 825.5640, 1, 0.817540583, 5.53, 7.50],
    [13, 679.3990, 1, -0.519099216, 5.44, 14.03],
    [14, 547.1537, 1, 1.886250910, 4.09, 8.81],
    [15, 914.7231, 0, 0.838316907, 5.93, 16.38],
    [16, 479.8623, 0, -0.546267153, 4.89, 10.57],
    [17, 949.1354, 0, -1.031261834, 7.73, 15.51],
    [18, 552.4339, 0, 1.398512189, 3.84, 13.52],
    [19, 872.8508, 1, 1.206541016, 4.02, 14.63],
    [20, 852.5014, 1, -1.727529136, 3.88, 15.80],
    [21, 668.0181, 1, 0.095158046, 4.91, 8.00],
    [22, 593.8212, 1, -0.228175134, 6.76, 9.49],
    [23, 837.5094, 0, -1.681509581, 5.53, 15.04],
    [24, 604.2461, 0, -0.431484912, 5.13, 10.88],
    [25, 1147.0011, 0, -0.767956014, 6.28, 19.73],
    [26, 1086.6442, 0, 0.409593287, 3.97, 17.97],
    [27, 440.2124, 1, 0.909462630, 4.50, 6.78],
    [28, 588.5289, 1, 0.225198950, 4.59, 5.07],
    [29, 748.1592, 1, -0.876883893, 4.41, 9.51],
    [30, 500.5018, 0, -0.636320587, 5.73, 9.72],
    [31, 453.1050, 1, 1.060164993, 4.94, 6.14],
    [32, 802.8014, 0, -1.924094546, 6.33, 11.38],
    [33, 924.7262, 1, -0.075940252, 6.42, 11.38],
    [34, 686.9229, 0, -0.987334055, 5.82, 11.91],
    [35, 779.7551, 0, -0.499456790, 5.59, 15.55],
    [36, 1067.8460, 0, -0.119138607, 4.02, 18.89],
    [37, 435.3211, 1, 0.055813553, 3.98, 5.20],
    [38, 672.8120, 1, -0.154608363, 3.92, 9.22],
    [39, 798.8885, 0, -0.675209438, 4.26, 15.03],
    [40, 887.5744, 0, 0.232633737, 4.45, 14.54],
    [41, 772.1471, 0, -1.153106896, 4.00, 14.19],
    [42, 711.8005, 1, -0.250870412, 5.18, 10.71],
    [43, 959.6500, 1, 2.937458237, 6.47, 13.61],
    [44, 798.6617, 1, -0.359408995, 5.50, 13.69],
    [45, 773.8696, 1, -0.078034563, 5.21, 11.44],
    [46, 1083.1070, 1, 0.031851193, 5.92, 16.94],
    [47, 946.0240, 0, 0.703861450, 5.90, 17.33],
    [48, 905.3671, 0, 0.053742313, 3.97, 16.01],
    [49, 727.4559, 1, 0.806395313, 4.82, 11.93],
    [50, 652.5204, 1, -0.247366388, 5.09, 8.71],
    [51, 730.2989, 1, 0.277855440, 4.35, 13.81],
    [52, 533.8203, 1, 0.280086781, 4.28, 10.44],
    [53, 771.9552, 0, 0.637483675, 5.79, 11.30],
    [54, 461.4010, 1, -0.892968784, 7.00, 6.27],
    [55, 712.1740, 0, 0.002846139, 5.13, 14.48],
    [56, 621.2516, 1, 0.637170276, 4.95, 13.12],
    [57, 1056.0942, 0, 1.103590199, 5.12, 18.61],
    [58, 845.6151, 1, 0.896929164, 3.59, 13.97],
    [59, 631.6037, 0, -0.860206372, 5.66, 13.92],
    [60, 653.4346, 1, 0.640849681, 7.85, 8.82],
    [61, 861.2259, 0, 1.324710360, 5.59, 14.87],
    [62, 1262.9367, 0, -0.464891924, 5.32, 19.41],
    [63, 497.6874, 1, -0.189651215, 5.17, 6.60],
    [64, 1156.4558, 0, 0.651017451, 5.76, 18.38],
    [65, 691.1441, 0, -1.283994261, 4.78, 13.33],
    [66, 641.1693, 1, -1.059388535, 5.69, 12.89],
    [67, 822.6072, 0, 1.308124963, 5.27, 15.44],
    [68, 532.8619, 1, -1.689259946, 3.46, 14.49],
    [69, 573.1658, 0, -0.566614671, 5.40, 11.39],
    [70, 617.8083, 1, 1.277734448, 3.91, 9.73],
    [71, 805.5647, 0, -0.101344968, 3.79, 17.03],
    [72, 1000.4114, 0, -0.317092816, 5.48, 16.77],
    [73, 526.1248, 1, 0.435627145, 5.00, 8.47],
    [74, 539.2825, 1, -0.055483708, 5.21, 5.60],
    [75, 1001.6186, 1, -0.136485334, 3.99, 17.29],
    [76, 793.4550, 0, -0.696743129, 5.01, 11.79],
    [77, 536.6613, 1, -0.181288443, 5.11, 6.67],
    [78, 860.3506, 0, -1.700202821, 5.65, 16.01],
    [79, 893.2638, 0, 0.041362189, 3.93, 17.27],
    [80, 438.5669, 0, -0.780838942, 4.57, 6.68],
    [81, 838.4197, 0, -0.545257859, 6.22, 14.99],
    [82, 674.3586, 0, 0.115885755, 6.14, 10.03],
    [83, 505.1645, 1, 1.497221152, 7.13, 7.72],
    [84, 931.4578, 0, -0.218447834, 3.53, 12.63],
    [85, 572.1907, 1, -0.075342743, 2.57, 12.59],
    [86, 859.5180, 1, 0.614535293, 5.09, 13.27],
    [87, 850.8536, 0, -0.799236813, 5.06, 15.07],
    [88, 392.4479, 1, -0.839749227, 5.22, 5.15],
    [89, 1064.9678, 0, -0.149402168, 5.61, 17.77],
    [90, 681.8418, 1, -0.960002238, 5.83, 11.87],
    [91, 515.2914, 1, 0.554066933, 3.54, 8.35],
    [92, 398.1778, 1, -1.846682238, 2.96, 7.18],
    [93, 866.3629, 0, -1.393459183, 4.63, 19.01],
    [94, 781.1624, 0, -0.781345032, 5.22, 15.71],
    [95, 359.3451, 1, -1.466066527, 4.86, 7.57],
    [96, 754.3050, 0, -1.557994762, 5.88, 14.58],
    [97, 510.8689, 1, 1.092512580, 4.93, 6.81],
    [98, 819.0607, 0, -0.342840352, 6.46, 11.33],
    [99, 598.7699, 0, -0.333634265, 5.91, 7.70],
    [100, 872.1409, 0, 0.254873787, 5.21, 14.92],
]

df = pd.DataFrame(data, columns=["index", "Y", "Y_bin", "X1", "X2", "X3"]).set_index("index")
df.index.name = None

df

            Y  Y_bin        X1    X2     X3
1    821.5460      0 -0.937614  4.01  14.25
2    969.5544      0  0.194259  4.66  16.30
3    696.9056      1  1.197007  5.66   8.04
4    948.9634      0  0.367137  5.85  17.28
5    462.7538      1  1.935986  5.99   6.78
..        ...    ...       ...   ...    ...
96   754.3050      0 -1.557995  5.88  14.58
97   510.8689      1  1.092513  4.93   6.81
98   819.0607      0 -0.342840  6.46  11.33
99   598.7699      0 -0.333634  5.91   7.70
100  872.1409      0  0.254874  5.21  14.92

[100 rows x 5 columns]